[package]
name = "ruspiro-brain"
authors = ["Andre Borrmann <pspwizard@gmx.de>"]
version = "0.1.0" # remember to update html_root_url
description = """
The ``brain`` provides the heart of the async "thinking"" of a **RusPiRo** bare metal kernel for the
Raspberry Pi
"""
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-brain/tree/v0.1.0"
documentation = "https://docs.rs/ruspiro-brain/0.1.0"
readme = "README.md"
keywords = ["RusPiRo", "baremetal", "raspberrypi", "brain", "async"]
categories = ["no-std", "embedded"]
edition = "2018"
links = "ruspiro-brain"


[badges]
travis-ci = { repository = "RusPiRo/ruspiro-brain", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]

[dev-dependencies]
assert_matches = "1.2"

[dependencies]
pin-utils = "0.1.0-alpha.4"
ruspiro-boot = { path = "../boot", version = "0.3", features = ["ruspiro_pi3", "with_panic"] }
ruspiro-singleton = { path = "../singleton", version = "0.3" }
ruspiro-lock = { path = "../lock", version = "0.3" }

[features]
singlecore = ["ruspiro-boot/singlecore"]
